# Generated by Django 3.0.4 on 2020-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='informe',
            field=models.CharField(choices=[(0, 'No'), (1, 'Sí')], default=1, max_length=10),
        ),
    ]
