# Generated by Django 3.0.4 on 2020-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_resultado_informe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='informe',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], default=1),
        ),
    ]
