# Generated by Django 3.0.4 on 2020-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_auto_20200410_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='informe',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sí')]),
        ),
    ]
