# Generated by Django 3.0.4 on 2020-04-09 22:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
        ('muestreos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('informacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('numero_muestras', models.IntegerField(choices=[(1, 'N1'), (2, 'N2'), (3, 'N3'), (4, 'N4'), (5, 'N5')], default=1)),
                ('numero_referencia_informe', models.CharField(blank=True, max_length=50, null=True)),
                ('superficie', models.CharField(choices=[('SI', 'si'), ('NO', 'no')], default='NO', max_length=30, verbose_name='¿Es una superficie?')),
                ('observaciones_informe', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='observaciones en informe')),
                ('transporte', models.CharField(blank=True, max_length=200, null=True)),
                ('muestreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestra_muestreo', to='muestreos.Muestreo')),
                ('parametros', models.ManyToManyField(to='parametros.Parametro')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
