# Generated by Django 3.0.4 on 2020-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='rango',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
