# Generated by Django 3.0.4 on 2020-04-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0002_muestra_rango'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='rango',
        ),
    ]
