# Generated by Django 3.0.4 on 2020-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
        ('muestras', '0004_auto_20200410_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='parametros',
            field=models.ManyToManyField(blank=True, to='parametros.Parametro'),
        ),
    ]
