# Generated by Django 3.0.4 on 2020-04-09 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nif', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('frecuencia', models.IntegerField(choices=[(0, 'sin determinar'), (15, '15 días'), (30, '1 mes'), (60, '2 meses'), (90, '3 meses'), (120, '4 meses'), (150, '5 meses'), (180, '6 meses')], default=0)),
                ('proxima_visita', models.DateField(default=datetime.datetime.now)),
                ('actividad', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
