# Generated by Django 3.0.4 on 2020-04-09 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.IntegerField(unique=True)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestra_cliente', to='clientes.Cliente')),
            ],
            options={
                'ordering': ['-referencia'],
            },
        ),
    ]
