# Generated by Django 3.0.4 on 2020-04-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_informe', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre en el informe de la muestra')),
                ('metodo_ensayo', models.CharField(blank=True, max_length=100, null=True)),
                ('presencia', models.CharField(choices=[('SI', 'sí'), ('NO', 'no')], default='NO', max_length=50, verbose_name='Determinar presencia o ausencia')),
                ('dilucion', models.CharField(choices=[('-1', '10^-1'), ('-2', '10^-2'), ('-3', '10^-3'), ('-4', '10^-4'), ('-5', '10^-5'), ('N/D', 'sin determinar')], default='N/D', max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
